name: device_ext_info
description: Device extended info fultter plugin
version: 0.0.1
homepage: https://github.com/Hacker-CB/flutter-device-ext-info
author: Pavel Sokolov <pavel@sokolov.me>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: me.sokolov.device_ext_info
    pluginClass: DeviceExtInfoPlugin

flutter_i18n:
  enable-flutter-i18n: false

